mapWidth: 57                   # map width
mapHeight: 33                  # map height
output: "warehouse_small2.map"  # output map file name
stationConfig: "station.txt"   # station layout
stationNumber: 1000            # number of stations
storageSize: [3,2]             # the block size of the storages [width, height]
stationDistance: 2             # distance between two consecutive emitters
corridorWidth: 1               # distance between two storage blocks
pillarWidth: 10                 # width of the pillar
operWidth: 5                   # distance between the pickup station and the storage area